import Head from 'next/head';
import { getCookie } from 'cookies-next';
import { GetServerSideProps } from 'next';

import Header from '@/components/Header/Header';
import Button from '@/components/Button/Button';
import Link from 'next/link';

export default function Home({
  address: cachedAddress,
}: {
  address: string | null;
}) {
  return (
    <>
      <Head>
        <title>Emergency Relief</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className="container mx-auto py-10">
        <Header cachedAddress={cachedAddress || undefined} />

        <main className="space-y-5 mt-8">
          <div className="grid grid-cols-12 gap-4 gap-y-8">
            <div className="flex flex-col flex-1 justify-between col-span-12 lg:col-span-8 py-8 px-6 rounded-3xl space-y-14 bg-[#F1F1EF]">
              <h1 className="text-4xl lg:text-7xl font-semibold">
                An international emergency
              </h1>

              <span className="text-lg block">
                Turkey has declared a state of emergency after two powerful
                earthquakes, with magnitudes of{' '}
                <Link
                  href="https://www.emsc-csem.org/Earthquake/earthquake.php?id=1218444"
                  target="_blank"
                >
                  7.8{' '}
                </Link>{' '}
                and{' '}
                <Link
                  href="https://www.emsc-csem.org/Earthquake/earthquake.php?id=1218771"
                  target="_blank"
                >
                  7.5
                </Link>
                , struck the country on 6 February 2023, resulting in over 40k+
                deaths, 6k+ collapsed buildings, and affecting over 23 million
                people.
              </span>

              <Link href="/donate">
                <Button className="!px-12" size="large">
                  Donate now
                </Button>
              </Link>
            </div>

            <div className="flex flex-1 flex-col justify-between col-span-12 lg:col-span-4 space-y-4">
              <div className="space-y-3 bg-[#F1F1EF] p-6 rounded-3xl">
                <Link
                  href="https://en.afad.gov.tr/press-bulletin-32-about-the-earthquake-in-kahramanmaras"
                  target="_blank"
                >
                  <h2 className="text-4xl font-semibold">40,000+</h2>
                  <span className="block text-lg">
                    Death toll from the latest official figures.
                  </span>
                </Link>
              </div>

              <div className="space-y-3 bg-[#F1F1EF] p-6 rounded-3xl">
                <Link
                  href="https://www.emsc-csem.org/Earthquake/earthquake.php?id=1218444"
                  target="_blank"
                >
                  <h2 className="text-4xl font-semibold">7.8</h2>
                  <span className="block text-lg">
                    Magnitudes of the mainshock and the largest aftershock.
                  </span>
                </Link>
              </div>

              <div className="space-y-3 bg-[#F1F1EF] p-6 rounded-3xl">
                <h2 className="text-4xl font-semibold">6,000+</h2>
                <span className="block text-lg">
                  Collapsed buildings on people trapped in the rubble.
                </span>
              </div>
            </div>
          </div>

          <div className="bg-[#F1F1EF] px-6 py-8 rounded-3xl">
            <h2 className="text-4xl font-semibold">About us</h2>
            <span className="mt-10 block text-lg">
              Emergency Relief is a data commons API that is initiated by the{' '}
              <Link href="https://twitter.com/inverternetwork/" target="_blank">
                {' '}
                Inverter Network{' '}
              </Link>
              , which is a community-driven infrastructure protocol for
              coordination and conditional streaming to foster open-source
              software development & research.{' '}
              <Link href="https://twitter.com/inverternetwork/" target="_blank">
                Inverter Network{' '}
              </Link>
              collaborates directly with development initiatives and grassroots
              projects on the ground.
              <br />
              <br />
              Our idea of creating the <Link href="/">
                emergencyrelief.xyz
              </Link>{' '}
              is to enable direct and informed contributions to the NGOs that
              are being mobilized in case of emergencies, this time that being
              the earthquake in Turkey & Syria. We are onboarding widely
              acclaimed verified NGOs to blockchain to help them receive fast,
              secure, global, and transparent aid. We are also working with some
              of them to create blockchain-based accountability methods to
              facilitate sustainable funding for development projects in the
              future.
              <br />
              <br />
              We built this data commons with{' '}
              <Link href="https://giveth.io/" target="_blank">
                Giveth{' '}
              </Link>{' '}
              and{' '}
              <Link href="https://gitcoin.co/" target="_blank">
                Gitcoin{' '}
              </Link>{' '}
              to enable other funding and donation platforms to easily work with
              those NGOs by pulling their digital identities easily into their
              platforms. To ensure the integrity and transparency of those
              donations with disaster relief, we only list NGOs that are KYC
              verified by{' '}
              <Link href="https://www.paribu.com/" target="_blank">
                Paribu Exchange
              </Link>
              , a major exchange in Turkey.
            </span>
          </div>
        </main>
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{
  address: string | null;
}> = async ({ req, res }) => {
  res.setHeader(
    'Cache-Control',
    'public, s-maxage=10, stale-while-revalidate=59',
  );

  const address = getCookie('address', { req, res });

  return {
    props: {
      address: address?.toString() || null,
    },
  };
};
